const data={
  "10001":{deed:"10001",doc:"โฉนดที่ดิน (ข้อมูลจำลอง)",location:"ตำบลบ้านตัวอย่าง · อำเภอเมืองสมมติ · จังหวัดสมมติ",area:"12 ไร่ (ข้อมูลจำลอง)",status:"ข้อมูลสถานะสิทธิ์ตามข้อมูลจำลอง",overlaps:[]},
  "10002":{deed:"10002",doc:"โฉนดที่ดิน (ข้อมูลจำลอง)",location:"ตำบลบ้านตัวอย่าง · อำเภอเมืองสมมติ · จังหวัดสมมติ",area:"8 ไร่ (ข้อมูลจำลอง)",status:"ข้อมูลสถานะสิทธิ์ตามข้อมูลจำลอง",overlaps:[["เขตป่าสงวนตัวอย่าง","เขตป่าสงวน"]]},
  "10003":{deed:"10003",doc:"โฉนดที่ดิน (ข้อมูลจำลอง)",location:"ตำบลบ้านตัวอย่าง · อำเภอเมืองสมมติ · จังหวัดสมมติ",area:"15 ไร่ (ข้อมูลจำลอง)",status:"ข้อมูลสถานะสิทธิ์ตามข้อมูลจำลอง",overlaps:[["เขต ส.ป.ก. ตัวอย่าง","เขต ส.ป.ก."],["เขตอุทยานตัวอย่าง","เขตอุทยาน"]]}
};
let method="deed";
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function go(id){$$('.page').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.go===id||(id==='result'&&x.dataset.go==='search')));window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-go]').forEach(x=>x.addEventListener('click',()=>go(x.dataset.go)));
function renderLayers(){
  const layers=[["parcel","แปลงที่ดิน","ขอบเขตแปลง · ข้อมูลจำลอง"],["spk","เขต ส.ป.ก.","หน่วยงานเจ้าของข้อมูล (จำลอง)"],["forest","เขตป่าสงวน","หน่วยงานเจ้าของข้อมูล (จำลอง)"],["park","เขตอุทยาน","หน่วยงานเจ้าของข้อมูล (จำลอง)"]];
  $('#layers').innerHTML=layers.map(([id,n,d])=>`<div class="layer"><div class="layer-line"><div><div class="layer-name">${n}</div><small>${d}</small></div><button class="switch on" aria-label="เปิด/ปิด ${n}" data-layer="${id}"></button></div></div>`).join('');
  $$('.switch').forEach(b=>b.onclick=()=>{b.classList.toggle('on');const id=b.dataset.layer;$$('.layer-'+id).forEach(e=>e.style.display=b.classList.contains('on')?'':'none')});
}
renderLayers();
$$('.parcel-shape').forEach(b=>b.onclick=()=>showResult(b.dataset.parcel));
$$('.tab').forEach(b=>b.onclick=()=>{method=b.dataset.method;$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$('#deed-box').classList.toggle('hidden',method!=='deed');$('#coord-box').classList.toggle('hidden',method!=='coord');$('#error').classList.add('hidden')});
$('#searchForm').onsubmit=e=>{e.preventDefault();const er=$('#error');er.classList.add('hidden');if(method==='deed'){const v=$('#deed').value.trim();if(!v)return err('กรุณากรอกเลขโฉนดก่อนค้นหา');if(!/^\d+$/.test(v))return err('เลขโฉนดควรเป็นตัวเลข');if(!data[v])return err('ไม่พบแปลงนี้ในข้อมูลจำลอง · ลอง 10001, 10002 หรือ 10003');showResult(v)}else{const a=Number($('#lat').value),b=Number($('#lng').value);if(!$('#lat').value||!$('#lng').value)return err('กรุณากรอกทั้งละติจูดและลองจิจูด');if(!Number.isFinite(a)||!Number.isFinite(b))return err('พิกัดต้องเป็นตัวเลข');if(a<18||a>20||b<98||b>100)return err('พิกัดอยู่นอกพื้นที่ตัวอย่าง');showResult('10001')}};
function err(t){$('#error').textContent=t;$('#error').classList.remove('hidden')}
function showResult(id){const p=data[id],has=p.overlaps.length;$('#result-title').textContent=`ผลการตรวจสอบแปลง ${p.deed}`;$('#result-root').innerHTML=`<div class="result-status ${has?'warn':''}"><b>${has?'⚠ พบการซ้อนทับตามข้อมูลจำลอง':'✓ ไม่พบการซ้อนทับตามข้อมูลจำลอง'}</b><br><span>${has?'ระบบพบเขตที่มีขอบเขตทับกับแปลงนี้ตามข้อมูลจำลอง':'ไม่พบการซ้อนทับกับเขตในชั้นข้อมูลที่ใช้ตรวจสอบ'}</span></div><div class="result-grid"><div class="result-card"><h2>รายละเอียดแปลง</h2><dl class="details"><dt>เลขโฉนด</dt><dd>${p.deed}</dd><dt>เอกสาร</dt><dd>${p.doc}</dd><dt>ที่ตั้ง</dt><dd>${p.location}</dd><dt>ขนาดพื้นที่</dt><dd>${p.area}</dd><dt>สถานะ</dt><dd>${p.status}</dd></dl></div><div class="result-card"><h2>การตรวจการซ้อนทับ</h2>${has?`<div class="overlap"><b>พบ ${p.overlaps.length} เขต</b><ul>${p.overlaps.map(x=>`<li><b>${x[0]}</b> — ${x[1]}</li>`).join('')}</ul></div>`:`<div class="result-status"><b>ไม่พบการซ้อนทับ</b><br>ตามชั้นข้อมูลจำลองที่เปิดใช้งาน</div>`}<h2 style="margin-top:20px">ตำแหน่งบนแผนที่</h2><div class="mini-map"><div class="zone z-spk">ส.ป.ก.</div><div class="zone z-forest">ป่าสงวน</div><div class="zone z-park">อุทยาน</div><div class="parcel-shape">${p.deed}</div></div></div></div><div class="disclaimer"><b>ข้อควรทราบ</b> ข้อมูลทั้งหมดเป็นข้อมูลจำลองเพื่อการเรียนรู้ ไม่ใช่คำวินิจฉัยหรือการรับรองสิทธิ์ตามกฎหมาย และไม่มีข้อมูลส่วนบุคคล</div><div class="actions"><button class="primary" onclick="go('search')">ค้นหาแปลงอื่น</button><button class="secondary" onclick="go('map')">กลับแผนที่</button></div>`;go('result')}
